#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
permissions:
  contents: write
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: ./.github/workflows/_extension_distribution.yml
    with:
      duckdb_version: v0.10.2
      extension_name: quack
      exclude_archs: 'linux_amd64;linux_arm64;linux_amd64_gcc4;windows_amd64;windows_amd64_rtools'

  duckdb-stable-deploy:
    name: Deploy extension binaries
    needs: duckdb-stable-build
    uses: ./.github/workflows/_extension_deploy.yml
    secrets: inherit
    with:
      duckdb_version: v0.10.2
      extension_name: quack
      deploy_latest: ${{ startsWith(github.ref, 'refs/tags/v') || github.ref == 'refs/heads/main' }}

  github_pages:
    name: Publish on Github pages
    needs: duckdb-stable-build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'gh-pages'

      - uses: actions/checkout@v4
        with:
          ref: 'main'
          path: build

      - uses: actions/download-artifact@v4
        with:
          pattern: extension_repository*
          path: build

      - name: Commit report
        run: |
          rsync -a build/extension_repository*/* .
          brew install duckdb
          cat build/boilerplate.md > README.md
          ./build/scripts/generated_docs_readme.sh >> README.md
          git rm -r build
          git config --global user.name 'Carlo Piovesan'
          git config --global user.email 'carlopi@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add -A
          git commit -m "Automated report"
          git push
