#
# This workflow calls the main distribution pipeline from DuckDB to build, test and (optionally) release the extension
#
name: Main Extension Distribution Pipeline
permissions:
  contents: write
  id-token: write
on:
  push:
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-${{ github.head_ref || '' }}-${{ github.base_ref || '' }}-${{ github.ref != 'refs/heads/main' || github.sha }}
  cancel-in-progress: true

env:
    EXTENSIONS: "quack"

jobs:
  duckdb-stable-build:
    name: Build extension binaries
    uses: ./.github/workflows/_extension_distribution.yml
    with:
      duckdb_version: v0.10.2
      extension_name: quack
      exclude_archs: 'linux_amd64;linux_arm64;linux_amd64_gcc4;windows_amd64;windows_amd64_rtools'

  github_pages:
    name: Publish on Github pages
    needs: duckdb-stable-build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: 'main'
          path: main

      - name: Create tag (if not there already)
        run: |
          cd main
          # Check whether gh-pages branch exists, if not, create it now
          _check_branch=$(git ls-remote --heads origin gh-pages)
          if [[ -z ${_check_branch} ]]; then
            git switch --orphan gh-pages
            git config --global user.name 'Carlo Piovesan'
            git config --global user.email 'carlopi@users.noreply.github.com'
            git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
            echo "... building" > README.md
            git add README.md
            git commit -m "Base commit, autogenerated, do not touch"
            git push --set-upstream origin gh-pages
            git checkout main
          fi

      - uses: actions/checkout@v4
        with:
          ref: 'gh-pages'
          path: pages

      - uses: actions/download-artifact@v4
        with:
          pattern: extension_repository*
          path: extensions

      - name: Commit report
        run: |
          rsync -a extensions/extension_repository*/* pages/.
          brew install duckdb
          cd pages
          cat ../main/boilerplate.md > README.md
          ../main/scripts/generated_docs_readme.sh ${EXTENSIONS} >> README.md
          git config --global user.name 'Carlo Piovesan'
          git config --global user.email 'carlopi@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add -A
          git commit --amend --no-edit
          git push -f
          cd ..
          tar -cvf pages.tar pages
          gzip pages.tar

      - uses: actions/upload-pages-artifact@v1
        with:
          path: pages.tar.gz
          name: github-pages

      - id: deployment
        uses: actions/deploy-pages@main
